### ISSUE TITLE
Add better post masking to pipeline

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/comp-pipeline#49]
Code written by Giuliana finds post in flats reliably and the post angle for the two beams is very close. The difference in the post angle between the two beams is less than 1degree. This should be our tolerance angle. However, the present code does not find the post angle correctly because of an error in the flat center.  This issue should be revisited once the center for the flat is fixed.

**Comment by mgalloy** [comment]
Don't mask post in L1 or intensity in L2. Everything else in the L2 should be masked. Use only the upper-left value for the post angle.

Also, need to have an epoch value to where to start searching: +-180.0 for before May 2016, 0.0 afterwards. Then only search around +- 30 (epoch value) that value for the post.

Can adjust value of `post_width` in epoch file, possibly adding a few pixels to 36.0.

**Comment by mgalloy** [comment]
f9304b868c97b263a7534d1262f8d27825446db3 produces warnings if post angles differ by more than `post_angle_diff_tolerance`.

**Comment by mgalloy** [comment]
Post finding is probably working, but we are not getting the correct distortion corrected centers into the flat headers.

**Comment by detoma** [comment]
Code written by Giuliana finds post in flats reliably and the post angle for the two beams is very close. The difference in the post angle between the two beams is less than 1degree. This should be our tolerance angle. However, the present code does not find the post angle correctly because of an error in the flat center. This issue should be revisited once the center for the flat is fixed.

**Comment by mgalloy** [comment]
Post masking should happen for level 2.

**Comment by mgalloy** [comment]
Post masking is happening in level2.

**Comment by mgalloy** [comment]
@detoma verifies this with the background GIFs.
